### ISSUE TITLE
Seg fault on close connection in initial

### ISSUE THREAD

**Issue by kenmcmil** [private-octopus/picoquic#340]
commit: cb34de2

Seg fault occurs when server receives an initial packet with client hello handshake message followed immediately by an initial packet with a connection close frame. It appears that the server tries to send a 1rtt propected packet as a response before the packet number encoder for this packet type has been initialized. Stack trace follows:

```
#0  0x000055555557a7bd in picoquic_pn_iv_size (pn_enc=0x0) at /home/mcmillan/projects/picoquic/picoquic/tls_api.c:1345
#1  0x000055555557227f in picoquic_protect_packet (cnx=0x5555557cb8e0, ptype=picoquic_packet_1rtt_protected_phi0, bytes=0x5555557cc67d "", sequence_number=0, length=18, header_length=13, send_buffer=0x7fffffffdbf0 "0", send_buffer_max=1252, aead_context=0x0, pn_enc=0x0) at /home/mcmillan/projects/picoquic/picoquic/sender.c:395
#2  0x0000555555572c4a in picoquic_finalize_and_protect_packet (cnx=0x5555557cb8e0, packet=0x5555557cc640, ret=0, length=18, header_length=13, checksum_overhead=16, send_length=0x7fffffffd2e8, send_buffer=0x7fffffffdbf0 "0", send_buffer_max=1252, path_x=0x5555557c7be0, current_time=1538606342246257) at /home/mcmillan/projects/picoquic/picoquic/sender.c:659
#3  0x000055555557617b in picoquic_prepare_packet_closing (cnx=0x5555557cb8e0, path_x=0x5555557c7be0, packet=0x5555557cc640, current_time=1538606342246257, send_buffer=0x7fffffffdbf0 "0", send_buffer_max=1252, send_length=0x7fffffffd2e8) at /home/mcmillan/projects/picoquic/picoquic/sender.c:2024
#4  0x0000555555576d68 in picoquic_prepare_segment (cnx=0x5555557cb8e0, path_x=0x5555557c7be0, packet=0x5555557cc640, current_time=1538606342246257, send_buffer=0x7fffffffdbf0 "0", send_buffer_max=1536, send_length=0x7fffffffd2e8) at /home/mcmillan/projects/picoquic/picoquic/sender.c:2314
#5  0x0000555555576f0a in picoquic_prepare_packet (cnx=0x5555557cb8e0, current_time=1538606342246257, send_buffer=0x7fffffffdbf0 "0", send_buffer_max=1536, send_length=0x7fffffffd388) at /home/mcmillan/projects/picoquic/picoquic/sender.c:2367
#6  0x00005555555610f1 in quic_server (server_name=0x55555559904c "::", server_port=4443, pem_cert=0x555555599028 "certs/cert.pem", pem_key=0x555555599037 "certs/key.pem", just_once=0, do_hrr=0, cnx_id_callback=0x0, cnx_id_callback_ctx=0x0, reset_seed=0x0, mtu_max=0) at /home/mcmillan/projects/picoquic/picoquicfirst/picoquicdemo.c:488
#7  0x000055555556395b in main (argc=1, argv=0x7fffffffe408) at /home/mcmillan/projects/picoquic/picoquicfirst/picoquicdemo.c:1305

```
Notice that pn_enc = 0x0 in stack frame 0.

Log follows:
```
Starting PicoQUIC server on port 4443, server name = ::, just_once = 0, hrr= 0
d: Receiving packet type: 2 (initial), S0, Version ff00000e,
d:     <000000000000000d>, <000000000000000d>, Seq: 0, pl: 1171
d:     Decrypted 1171 bytes
d:     Crypto HS frame, offset 0, length 398: 0100018a0303a964...
d:     padding, 769 bytes

d: 0.002133 : Connection established, state = 11, from length: 16
d: Client address: 127.0.0.1, port 31507
d: Received SNI: localhost
d: ALPN not received.
d: Did not receive transport parameter TLS extension.
d: Sending packet type: 2 (initial), S0, Version ff00000e,
d:     <000000000000000d>, <125373ecba25e79e>, Seq: 0, pl: 132
d:     Prepared 132 bytes
d:     ACK (nb=0), 0
d:     Crypto HS frame, offset 0, length 123: 020000770303b489...

d: Sending packet type: 4 (handshake), S0, Version ff00000e,
d:     <000000000000000d>, <125373ecba25e79e>, Seq: 0, pl: 1031
d:     Prepared 1031 bytes
d:     Crypto HS frame, offset 0, length 1027: 0800000600040000...

d: Connection state = 6
d: Sending packet type: 4 (handshake), S0, Version ff00000e,
d:     <000000000000000d>, <125373ecba25e79e>, Seq: 1, pl: 132
d:     Prepared 132 bytes
d:     Crypto HS frame, offset 1027, length 127: d3524ce5075984f2...

d: Sending packet type: 6 (1rtt protected phi0), S0,
d:     <000000000000000d>, Seq: 0 (0)
d:     Prepared 141 bytes
d:     Crypto HS frame, offset 0, length 137: 04000085000186a0...

d: Sending packet type: 6 (1rtt protected phi0), S0,
d:     <000000000000000d>, Seq: 1 (1)
d:     Prepared 1411 bytes
d:     ping, 1 bytes
d:     padding, 1410 bytes

2: Receiving packet type: 2 (initial), S0, Version ff00000e,
2:     <0000000000000002>, <000000000000000d>, Seq: 1, pl: 1171
2:     Decrypted 1171 bytes
2:     connection_close, Error 0xc654, Offending frame afd4
Reason length 1
2:     connection_close, Error 0xf3e5, Offending frame b62d
Reason length 1
2:     padding, 1153 bytes

2: 0.000099 : Server CB, Stream: 0, 0 bytes, fin=5 (connection close)
2: 0.000103 : Server CB, Stream: 0, 0 bytes, fin=5 (connection close)
2: 0.000109 : Connection established, state = 15, from length: 16
2: Client address: 127.0.0.1, port 31507
2: SNI not received.
2: ALPN not received.
2: Did not receive transport parameter TLS extension.

```

**Comment by huitema** [comment]
Thanks for the report. Working on it asap tomorrow.

**Comment by huitema** [comment]
I just set a test case to repro the issue. I cannot quite reproduce the crash, probably due to some timing conditions. @kenmcmil was your close message frame carried by the same packet as the client hello? But I see that there is indeed a bug, because the server attempts to send its own connection close message using 1RTT, and that is clearly wrong.

**Comment by huitema** [comment]
Fixed in PR #345

**Comment by kenmcmil** [comment]
Hi @huitema. The close connection frame was actually in a different packet from the client hello. In fact, that packet may have been a protocol violation, but I thought I would open an issue since it was a seg fault.  I'm working on a randomized tester for QUIC based on a formal specification of the protocol. The spec is still incomplete so sometimes it acts more like a protocol fuzzer.

**Comment by huitema** [comment]
Thanks for testing. I have added a specific fuzzing step for the initial packet. And I have also fixed the bug that caused the crash.
